encryption_key: $DB_ENCRYPTION_KEY

source:
  connection_uri: $DATABASE_URL

datastore:
  aws:
    bucket: $BUCKET_NAME
    region: eu-central-1
    credentials:
      access_key_id: $ACCESS_KEY_ID
      secret_access_key: $AWS_SECRET_ACCESS_KEY

destination:
  connection_uri: $PYCON_BACKEND_DB_URL
