version: 2

defaults_node: &defaults_node
  docker:
    - image: circleci/node:8.11@sha256:6541a5bd51fd81f362dac9dd78cb9a5fc1d08bb46691bdca24e98558eba48276

jobs:
  backend-test:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1@sha256:6a9bbe17f3ecc54fb6be875b8c6c8eaed84eadc2b1fd1b7d6e5c89da0381f625

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # store dependencies md5 in a single file
      # so that it can be used with checksum
      - run: find backend/requirements -type f -exec md5sum {} \; | sort -k 2 | md5sum > backend_deps_checksum

      # Download and cache dependencies
      - restore_cache:
          keys:
          - backend-{{ checksum "backend_deps_checksum" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r backend/requirements/test.txt

      - save_cache:
          paths:
            - ./venv
          key: backend-{{ checksum "backend_deps_checksum" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd backend
            py.test --cov-report xml --cov=. --cov-fail-under 100

      - run:
          name: upload codacy report
          command: |
            . venv/bin/activate
            cd backend
            python-codacy-coverage -r coverage.xml
          environment:
            CODACY_PROJECT_TOKEN: b371fba19b824c62ad6270d4e1f3b410

  frontend-lint:
    <<: *defaults_node
    steps:
      - checkout
      - restore_cache:
          key: frontend-cache-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: yarn
          command: yarn
          working_directory: ./frontend
      - save_cache:
          key: frontend-cache-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules
            - "~/.cache/yarn"
      - run:
          name: lint
          command: yarn run tslint --project .
          working_directory: ./frontend

workflows:
  version: 2

  checks:
    jobs:
      - backend-test
      - frontend-lint
