version: 2

defaults_node: &defaults_node
  docker:
    - image: circleci/node:8.11@sha256:dc90fd61468fbf9e6c008211fb7294c20970be9279f0d930b8ca0fdb2441eee0

jobs:
  frontend-deps:
    <<: *defaults_node

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: frontend-cache-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
      - run:
          command: yarn install
          working_directory: ./frontend
      - save_cache:
          key: frontend-cache-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules
            - "~/.cache/yarn"
      - persist_to_workspace:
            root: .
            paths:
                - frontend/node_modules/

  check-files:
    docker:
      - image: circleci/python:3.7.4

    working_directory: ~/repo

    steps:
      - checkout
      - attach_workspace:
            at: .
      - run: pip install --user pre-commit
      - run: ~/.local/bin/pre-commit run --all-files

  backend-test:
    docker:
      - image: circleci/python:3.7.4
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    working_directory: ~/repo

    steps:
      - checkout
      - run: find backend/requirements -type f -exec md5sum {} \; | sort -k 2 | md5sum > backend_deps_checksum
      - restore_cache:
          keys:
          - backend-{{ checksum "backend_deps_checksum" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r backend/requirements/test.txt
            pip install codecov

      - save_cache:
          paths:
            - ./venv
          key: backend-{{ checksum "backend_deps_checksum" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd backend
            set +e
            OUTPUT=$(py.test --cov-report xml --cov=. --cov-fail-under 100)
            STATUS=$?
            echo "$OUTPUT"
            codecov
            exit $STATUS

      - run:
          name: run integration tests
          command: |
            . venv/bin/activate
            cd backend
            py.test integration_tests/

  backend-schema:
    docker:
      - image: circleci/python:3.7.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: find backend/requirements -type f -exec md5sum {} \; | sort -k 2 | md5sum > backend_deps_checksum
      - restore_cache:
          keys:
          - backend-{{ checksum "backend_deps_checksum" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r backend/requirements/prod.txt

      - save_cache:
          paths:
            - ./venv
          key: backend-{{ checksum "backend_deps_checksum" }}

      - run:
          name: run tests
          environment:
            DJANGO_SETTINGS_MODULE: pycon.settings.dev
          command: |
            . venv/bin/activate
            cd backend
            python manage.py graphql_schema
            mv schema.json ../frontend/schema.json

      - persist_to_workspace:
          root: .
          paths:
            - frontend/schema.json

  frontend-tsc:
    <<: *defaults_node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: frontend-cache-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: yarn
          command: yarn
          working_directory: ./frontend
      - save_cache:
          key: frontend-cache-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules
            - "~/.cache/yarn"
      - run:
          name: typescript
          command: yarn run tsc
          working_directory: ./frontend

workflows:
  version: 2

  checks:
    jobs:
      - frontend-deps

      - check-files:
          requires:
            - frontend-deps

      - backend-test
      - backend-schema

      - frontend-tsc:
          requires:
            - frontend-deps
            - backend-schema
