name: Deploy

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  deploy-site:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - run: yarn
      working-directory: frontend
    - run: yarn codegen-fragments
      working-directory: frontend
      env:
        API_URL: https://d1111jewijk23m.cloudfront.net/graphql
    - run: yarn build
      working-directory: frontend
      env:
        CONFERENCE_CODE: pycon11
        API_URL: https://d1111jewijk23m.cloudfront.net/graphql
        API_TOKEN: ${{ secrets.API_TOKEN }}
    - uses: netlify/actions/cli@master
      with:
        args: deploy --dir=frontend/public --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
