name: Python Lint

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: users-backend
            driver: postgresql+asyncpg
          - name: association-backend
            driver: postgresql
    defaults:
      run:
        working-directory: ./${{ matrix.service.name }}
    services:
      postgres:
        image: postgres:11.10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.5"
      - run: pip install poetry
        if: steps.changed.outputs.changed.${{ matrix.service.name }} == 'true'
      - name: Set Poetry config
        if: steps.changed.outputs.changed.${{ matrix.service.name }} == 'true'
        run: poetry config virtualenvs.path ~/.virtualenvs
      - name: Cache Poetry
        if: steps.changed.outputs.changed.${{ matrix.service.name }} == 'true'
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ matrix.service.name }}-${{ hashFiles('**/poetry.lock') }}-v2
      - name: Install deps
        if: steps.changed.outputs.changed.${{ matrix.service.name }} == 'true'
        run: poetry install
      - name: Unit tests
        if: steps.changed.outputs.changed.${{ matrix.service.name }} == 'true'
        run: poetry run task test
        env:
          DATABASE_URL: ${{ matrix.service.driver }}://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres
          IDENTITY_SECRET: 'secret'
          PASTAPORTO_SECRET: 'secret'
          SERVICE_TO_SERVICE_SECRET: 'secret'
          SECRET_KEY: 'secret'
          STRIPE_SECRET_API_KEY: 'secret_stripe_key'
          STRIPE_SUBSCRIPTION_PRICE_ID: 'secret_price_id'
          STRIPE_WEBHOOK_SIGNATURE_SECRET: 'secret_webhook'
          ASSOCIATION_FRONTEND_URL: "https://associazione.python.it"
